import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {prepareEmail,claimEmail,recordReceipt,outboxSummary,dispatchBatch,recordDeliveryFailure} from '../scripts/application-outbox.mjs';
function fixture(){const root=mkdtempSync(join(tmpdir(),'outbox-'));mkdirSync(join(root,'data'));writeFileSync(join(root,'cv.pdf'),'%PDF-fixture');writeFileSync(join(root,'data','mail-history-threads.json'),JSON.stringify({threads:[]}));const checked_at=new Date().toISOString();return {root,plan:{company:'Example',role:'Engineering',kind:'open_application',url:'https://example.org/careers',to:'jobs@example.org',subject:'Application',html:'<p>Source-backed experience</p>',pdf:'cv.pdf',route:{source_url:'https://example.org/careers',email:'jobs@example.org',accepts_applications:true,evidence:'Email applications welcome',checked_at},history:{searched_all_sent:true,matches:0,checked_at},review:{facts_checked:true,pdf_visual_checked:true,blacklist_checked:true}}};}
const auth={automatic_send:true,user_instruction:'Send my job applications automatically'};
test('delivery failure preserves send evidence and cannot match another recipient',()=>{const {root,plan}=fixture();try{const {id}=prepareEmail(root,plan);claimEmail(root,id,auth);recordReceipt(root,id,{id:'m1',label_ids:['SENT']});assert.throws(()=>recordDeliveryFailure(root,id,{recipient:'other@example.org',message_id:'b1',reason:'550'}),/Matching/);recordDeliveryFailure(root,id,{recipient:plan.to,message_id:'b1',reason:'550 unknown recipient'});const summary=outboxSummary(root);assert.equal(summary.sent,1);assert.equal(summary.failed_delivery,1);assert.equal(summary.rows[0].receipt.id,'m1');assert.throws(()=>claimEmail(root,id,auth),/EEXIST/);}finally{rmSync(root,{recursive:true,force:true});}});
test('100-entry automatic dispatch is bounded by the user grant and stops on an ambiguous transport outcome',async()=>{const {root,plan}=fixture();try{for(let i=0;i<101;i++)prepareEmail(root,{...plan,company:'Example '+i,to:`jobs@ex${i}.org`,url:`https://ex${i}.org/careers`,route:{...plan.route,email:`jobs@ex${i}.org`,source_url:`https://ex${i}.org/careers`}});let calls=0;const grant={...auth,target:100,authorized_at:'grant1'};await dispatchBatch({root,authorization:grant,limit:101,transport:async()=>({id:'m'+(++calls),label_ids:['SENT']})});assert.equal(calls,100);assert.equal(outboxSummary(root).ready,1);const result=await dispatchBatch({root,authorization:{...auth,authorized_at:'grant2'},transport:async()=>{calls++;throw Error('connection lost after possible send');}});assert.equal(result[0].state,'unknown');await dispatchBatch({root,authorization:auth,transport:async()=>{calls++;}});assert.equal(calls,101);assert.equal(outboxSummary(root).unknown,1);}finally{rmSync(root,{recursive:true,force:true});}});
test('one durable send attempt; unknown outcomes never retry; receipts require Gmail SENT',()=>{const {root,plan}=fixture();try{const {id}=prepareEmail(root,plan);assert.throws(()=>claimEmail(root,id,{}),/authorization/);const payload=claimEmail(root,id,auth);assert.equal(payload.to,plan.to);assert.equal(Buffer.from(payload.payload.parts[1].body.base64_url_content,'base64url').toString(),'%PDF-fixture');assert.throws(()=>claimEmail(root,id,auth),/EEXIST/);assert.throws(()=>prepareEmail(root,plan),/dispatched/);assert.throws(()=>recordReceipt(root,id,{id:'draft',label_ids:['DRAFT']}),/SENT/);assert.equal(outboxSummary(root).unknown,1);recordReceipt(root,id,{id:'m1',thread_id:'t',label_ids:['SENT']});assert.equal(outboxSummary(root).sent,1);assert.equal(recordReceipt(root,id,{id:'m1',label_ids:['SENT']}).receipt.id,'m1');assert.throws(()=>recordReceipt(root,id,{id:'m2',label_ids:['SENT']}),/Conflicting/);}finally{rmSync(root,{recursive:true,force:true});}});
test('stale evidence, changed attachment and prior outreach block dispatch',()=>{const {root,plan}=fixture();try{let {id}=prepareEmail(root,plan);assert.throws(()=>claimEmail(root,id,auth,Date.now()+90000000),/expired/);writeFileSync(join(root,'cv.pdf'),'%PDF-changed');assert.throws(()=>claimEmail(root,id,auth),/changed/);({id}=prepareEmail(root,plan));writeFileSync(join(root,'data','mail-history-threads.json'),JSON.stringify({threads:[{messages:[{sent:true,to:'jobs@example.org'}]}]}));assert.throws(()=>claimEmail(root,id,auth),/Prior contact/);assert.throws(()=>prepareEmail(root,{...plan,pdf:'../outside.pdf'}),/outside/);assert.throws(()=>prepareEmail(root,{...plan,to:'jobs@example.org\r\nBcc:x@x.org'}),/Invalid/);}finally{rmSync(root,{recursive:true,force:true});}});
